apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - ../../../../components/applications/keycloak

# Dev-specific patches
# patches:
#   - patch: |-
#       - op: replace
#         path: /spec/resources/requests/storage
#         value: 5Gi
#     target:
#       kind: PersistentVolumeClaim
#       name: mssql-data
