apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: workbench-saas
spec:
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: 8024
    targetPort: 8024
  type: ClusterIP
